app.name=Kimwanyi SACCO Management System
app.environment=${APP_ENVIRONMENT:development}

db.url=jdbc:mysql://localhost:3306/sacco
db.username=root
db.password=KmaciS_394846
db.driver=com.mysql.cj.jdbc.Driver

hibernate.hbm2ddl.auto=${HIBERNATE_DDL_AUTO:update}
hibernate.show_sql=${HIBERNATE_SHOW_SQL:false}
hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

app.initial-admin.username=admin
app.initial-admin.password=admin
app.initial-admin.email=admin@kimwanyisacco.com

mail.enabled=${MAIL_ENABLED:false}
mail.host=${MAIL_HOST:smtp.gmail.com}
mail.port=${MAIL_PORT:587}
mail.username=${MAIL_USERNAME:samuelkala2003@gmail.com}
mail.password=${MAIL_PASSWORD:eikx tqnw tzel wphh}
mail.from=${MAIL_FROM:${MAIL_USERNAME:samuelkala2003@gmail.com}}
