package com.kimwanyi.model.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,

    MEMBER_REGISTERED,
    MEMBER_APPROVED,
    MEMBER_UPDATED,
    MEMBER_DEACTIVATED,

    DEPOSIT_PROCESSED,
    WITHDRAWAL_PROCESSED,

    LOAN_APPLIED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_REPAYMENT_RECORDED,

    INTERNAL_TRANSFER_COMPLETED,
    INTERNAL_TRANSFER_FAILED,

    PASSWORD_CHANGED,

    USER_ACCOUNT_ENABLED,
    USER_ACCOUNT_DISABLED
    ,EMAIL_SENT
    ,EMAIL_FAILED
}
